require directory for downloading llvm

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -49,6 +49,10 @@ proj_root_dir="$(cd "$(dirname "$0")" && pwd)"
 # Include the projects directory in the right CMakeFiles.txt file
 # under clang's project tree, in order to be able to build it.
 makelist="${llvm_src_dir}/tools/clang/tools/extra/CMakeLists.txt"
+if [ ! -e $makelist ]; then
+  echo -e "Clang and clang-extra-tools are required to build this project."
+  exit 1
+fi
 if ! grep -q ${proj_root_dir} ${makelist}; then
   echo -e "\nadd_subdirectory(${proj_root_dir} ${proj_root_dir})\n" >> ${makelist}
 fi
