add checks for cmake and g++

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22,6 +22,12 @@ command -v cmake >/dev/null 2>&1 || {
   exit 1;
 }
 
+command -v g++ >/dev/null 2>&1 || {
+  echo -e "g++ is required to build this project. Aborting..." >&2;
+  echo -e "hint: apt-get install build-essential\n" >&2;
+  exit 1;
+}
+
 if [ -d "$1" ]; then
   llvm_src_dir="$(cd "$1" && pwd)"
 else
